name: CMake

on:
  push:
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build-cuda:
    uses: ./.github/workflows/cmake-action.yml
    with:
      cuda-version: "12.2.0"

  build-cuda-11-7:
    needs: build-cuda
    uses: ./.github/workflows/cmake-action.yml
    with:
      cuda-version: "11.7.0"

  build-cuda-12-0:
    needs: build-cuda
    uses: ./.github/workflows/cmake-action.yml
    with:
      cuda-version: "12.0.0"
